services:
    bb3mobi.exlinks.controller:
        class: bb3mobi\exlinks\controller\url
        arguments:
            - @template
            - @user
            - @config
            - @bb3mobi.exlinks.convert
    bb3mobi.exlinks.helper:
        class: bb3mobi\exlinks\core\helper
        arguments:
            - @config
            - @config_text
            - @user
            - @controller.helper
    bb3mobi.exlinks.listener:
        class: bb3mobi\exlinks\event\listener
        arguments:
            - @bb3mobi.exlinks.helper
        tags:
            - { name: event.listener }
    bb3mobi.exlinks.convert:
        class: bb3mobi\exlinks\idna_convert
